-- Tạo bảng posts theo schema chuẩn
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_email text,
  title text default 'Bài viết mới' not null,
  content text not null,
  created_at timestamp with time zone default now() not null
);

-- Tương thích ngược: nếu bảng cũ dùng cột email thì copy sang user_email
alter table public.posts
  add column if not exists user_email text;

-- Tương thích ngược: nếu bảng cũ thiếu cột title thì thêm default để tránh lỗi NOT NULL khi insert
alter table public.posts
  add column if not exists title text default 'Bài viết mới';

-- Đảm bảo insert không bị fail khi cột title đang NOT NULL
alter table public.posts
  alter column title set default 'Bài viết mới';

update public.posts
set title = 'Bài viết mới'
where title is null;

alter table public.posts
  alter column title set not null;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'email'
  ) then
    execute 'update public.posts set user_email = coalesce(user_email, email) where user_email is null';
  end if;
end $$;

-- Đảm bảo cột email người dùng luôn có dữ liệu
alter table public.posts
  alter column user_email set not null;

-- Bật RLS
alter table public.posts enable row level security;

-- Tạo lại policy để tránh xung đột khi chạy nhiều lần
drop policy if exists "Authenticated users can read posts" on public.posts;
create policy "Authenticated users can read posts"
on public.posts
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert posts (user_email)" on public.posts;
drop policy if exists "Authenticated users can insert posts (email)" on public.posts;
drop policy if exists "Authenticated users can insert posts" on public.posts;

-- Policy insert cho schema chuẩn user_email
create policy "Authenticated users can insert posts (user_email)"
on public.posts
for insert
to authenticated
with check (auth.email() = user_email);

-- Nếu có cột email legacy thì thêm policy tương thích
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'email'
  ) then
    execute '
      create policy "Authenticated users can insert posts (email)"
      on public.posts
      for insert
      to authenticated
      with check (auth.email() = email)
    ';
  end if;
end $$;
