-- POSTS
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_email text,
  title text default 'Bài viết mới' not null,
  content text not null,
  image_url text,
  music_url text,
  created_at timestamp with time zone default now() not null
);

alter table public.posts add column if not exists user_email text;
alter table public.posts add column if not exists title text default 'Bài viết mới';
alter table public.posts add column if not exists image_url text;
alter table public.posts add column if not exists music_url text;
alter table public.posts alter column title set default 'Bài viết mới';
update public.posts set title = 'Bài viết mới' where title is null;
alter table public.posts alter column title set not null;

-- migrate legacy email column
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'posts' AND column_name = 'email'
  ) THEN
    EXECUTE 'update public.posts set user_email = coalesce(user_email, email) where user_email is null';
  END IF;
END $$;

alter table public.posts alter column user_email set not null;
alter table public.posts enable row level security;

drop policy if exists "Authenticated users can read posts" on public.posts;
create policy "Authenticated users can read posts"
on public.posts for select to authenticated using (true);

drop policy if exists "Authenticated users can insert posts (user_email)" on public.posts;
drop policy if exists "Authenticated users can insert posts (email)" on public.posts;
create policy "Authenticated users can insert posts (user_email)"
on public.posts for insert to authenticated
with check (auth.email() = user_email);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'posts' AND column_name = 'email'
  ) THEN
    EXECUTE '
      create policy "Authenticated users can insert posts (email)"
      on public.posts for insert to authenticated
      with check (auth.email() = email)
    ';
  END IF;
END $$;

-- SPECIAL DAYS
create table if not exists public.special_days (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  description text,
  image_url text,
  created_by uuid default auth.uid(),
  created_at timestamp with time zone default now() not null
);

alter table public.special_days enable row level security;

drop policy if exists "Authenticated users can read special days" on public.special_days;
create policy "Authenticated users can read special days"
on public.special_days for select to authenticated using (true);

drop policy if exists "Authenticated users can insert special days" on public.special_days;
create policy "Authenticated users can insert special days"
on public.special_days for insert to authenticated
with check (created_by = auth.uid() or created_by is null);

drop policy if exists "Authenticated users can delete own special days" on public.special_days;
create policy "Authenticated users can delete own special days"
on public.special_days for delete to authenticated
using (created_by = auth.uid() or created_by is null);
