-- Tạo bảng posts theo schema chuẩn
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_email text,
  content text not null,
  created_at timestamp with time zone default now() not null
);

-- Tương thích ngược: nếu bảng cũ dùng cột email thì copy sang user_email
alter table public.posts
  add column if not exists user_email text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'email'
  ) then
    execute 'update public.posts set user_email = coalesce(user_email, email) where user_email is null';
  end if;
end $$;

-- Đảm bảo cột email người dùng luôn có dữ liệu
alter table public.posts
  alter column user_email set not null;

-- Bật RLS
alter table public.posts enable row level security;

-- Tạo lại policy để tránh xung đột khi chạy nhiều lần
drop policy if exists "Authenticated users can read posts" on public.posts;
create policy "Authenticated users can read posts"
on public.posts
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert posts" on public.posts;
create policy "Authenticated users can insert posts"
on public.posts
for insert
to authenticated
with check (auth.email() = user_email);
